//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 05:01:26 PM PST 
//


package plm.ws.mtom.datacheck;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the plm.ws.mtom.datacheck package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InternalParoleeDataCheckRequest_QNAME = new QName("http://www.plm/ws/mtom/datacheck", "InternalParoleeDataCheckRequest");
    private final static QName _InternalParoleeDataCheckResponse_QNAME = new QName("http://www.plm/ws/mtom/datacheck", "InternalParoleeDataCheckResponse");
    private final static QName _UpdateAvailable_QNAME = new QName("http://www.plm/ws/mtom/datacheck", "UpdateAvailable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: plm.ws.mtom.datacheck
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InternalParoleeDataCheckRequest }
     * 
     */
    public InternalParoleeDataCheckRequest createInternalParoleeDataCheckRequest() {
        return new InternalParoleeDataCheckRequest();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link InternalParoleeDataCheckResponse }
     * 
     */
    public InternalParoleeDataCheckResponse createInternalParoleeDataCheckResponse() {
        return new InternalParoleeDataCheckResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternalParoleeDataCheckRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/datacheck", name = "InternalParoleeDataCheckRequest")
    public JAXBElement<InternalParoleeDataCheckRequest> createInternalParoleeDataCheckRequest(InternalParoleeDataCheckRequest value) {
        return new JAXBElement<InternalParoleeDataCheckRequest>(_InternalParoleeDataCheckRequest_QNAME, InternalParoleeDataCheckRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternalParoleeDataCheckResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/datacheck", name = "InternalParoleeDataCheckResponse")
    public JAXBElement<InternalParoleeDataCheckResponse> createInternalParoleeDataCheckResponse(InternalParoleeDataCheckResponse value) {
        return new JAXBElement<InternalParoleeDataCheckResponse>(_InternalParoleeDataCheckResponse_QNAME, InternalParoleeDataCheckResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/datacheck", name = "UpdateAvailable")
    public JAXBElement<String> createUpdateAvailable(String value) {
        return new JAXBElement<String>(_UpdateAvailable_QNAME, String.class, null, value);
    }

}
