//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 05:01:26 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.plm/ws/mtom/datacheck", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package plm.ws.mtom.datacheck;
