//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.25 at 11:09:54 PM PDT 
//

package plm.ws.mtom.photo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="County" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IsParoleePAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CDCNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AliasLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AliasFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Moniker" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Zip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BirthState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HeightInInches" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SSN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CIINumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FBINumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicensePlate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/photo}ParoleeReleaseDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/photo}VehicleYear" minOccurs="0"/>
 *         &lt;element name="Ethnicity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HairColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC290SexOff" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC4571Arson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC11590Drugs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC30586FelonyViolation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/photo}SMT" minOccurs="0"/>
 *         &lt;element name="CommitmentOffense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountyOfLLR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnitCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "lastUpdateDate", "city", "county",
		"isParoleePAL", "cdcNumber", "lastName", "firstName", "middleName",
		"aliasLastName", "aliasFirstName", "moniker", "zip", "birthState",
		"heightInInches", "weight", "ssn", "ciiNumber", "fbiNumber",
		"licensePlate", "dateOfBirth", "paroleeReleaseDate", "vehicleYear",
		"ethnicity", "hairColor", "pc290SexOff", "pc4571Arson", "pc11590Drugs",
		"pc30586FelonyViolation", "smt", "commitmentOffense", "countyOfLLR",
		"unitCode" })
@XmlRootElement(name = "SearchCriteria")
public class SearchCriteria {

	@XmlElement(name = "LastUpdateDate")
	protected String lastUpdateDate;
	@XmlElement(name = "City")
	protected String city;
	@XmlElement(name = "County")
	protected List<String> county;
	@XmlElement(name = "IsParoleePAL")
	protected String isParoleePAL;
	@XmlElement(name = "CDCNumber")
	protected String cdcNumber;
	@XmlElement(name = "LastName")
	protected String lastName;
	@XmlElement(name = "FirstName")
	protected String firstName;
	@XmlElement(name = "MiddleName")
	protected String middleName;
	@XmlElement(name = "AliasLastName")
	protected String aliasLastName;
	@XmlElement(name = "AliasFirstName")
	protected String aliasFirstName;
	@XmlElement(name = "Moniker")
	protected String moniker;
	@XmlElement(name = "Zip")
	protected String zip;
	@XmlElement(name = "BirthState")
	protected String birthState;
	@XmlElement(name = "HeightInInches")
	protected String heightInInches;
	@XmlElement(name = "Weight")
	protected String weight;
	@XmlElement(name = "SSN")
	protected String ssn;
	@XmlElement(name = "CIINumber")
	protected String ciiNumber;
	@XmlElement(name = "FBINumber")
	protected String fbiNumber;
	@XmlElement(name = "LicensePlate")
	protected String licensePlate;
	@XmlElement(name = "DateOfBirth")
	protected String dateOfBirth;
	@XmlElement(name = "ParoleeReleaseDate")
	protected ParoleeReleaseDate paroleeReleaseDate;
	@XmlElement(name = "VehicleYear")
	protected VehicleYear vehicleYear;
	@XmlElement(name = "Ethnicity")
	protected String ethnicity;
	@XmlElement(name = "HairColor")
	protected String hairColor;
	@XmlElement(name = "PC290SexOff")
	protected String pc290SexOff;
	@XmlElement(name = "PC4571Arson")
	protected String pc4571Arson;
	@XmlElement(name = "PC11590Drugs")
	protected String pc11590Drugs;
	@XmlElement(name = "PC30586FelonyViolation")
	protected String pc30586FelonyViolation;
	@XmlElement(name = "SMT")
	protected SMT smt;
	@XmlElement(name = "CommitmentOffense")
	protected String commitmentOffense;
	@XmlElement(name = "CountyOfLLR")
	protected String countyOfLLR;
	@XmlElement(name = "UnitCode")
	protected String unitCode;

	/**
	 * Gets the value of the lastUpdateDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLastUpdateDate() {
		return lastUpdateDate;
	}

	/**
	 * Sets the value of the lastUpdateDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLastUpdateDate(String value) {
		this.lastUpdateDate = value;
	}

	/**
	 * Gets the value of the city property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * Sets the value of the city property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCity(String value) {
		this.city = value;
	}

	/**
	 * Gets the value of the county property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the county property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCounty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getCounty() {
		if (county == null) {
			county = new ArrayList<String>();
		}
		return this.county;
	}

	/**
	 * Gets the value of the isParoleePAL property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIsParoleePAL() {
		return isParoleePAL;
	}

	/**
	 * Sets the value of the isParoleePAL property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIsParoleePAL(String value) {
		this.isParoleePAL = value;
	}

	/**
	 * Gets the value of the cdcNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCDCNumber() {
		return cdcNumber;
	}

	/**
	 * Sets the value of the cdcNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCDCNumber(String value) {
		this.cdcNumber = value;
	}

	/**
	 * Gets the value of the lastName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Sets the value of the lastName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLastName(String value) {
		this.lastName = value;
	}

	/**
	 * Gets the value of the firstName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Sets the value of the firstName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFirstName(String value) {
		this.firstName = value;
	}

	/**
	 * Gets the value of the middleName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMiddleName() {
		return middleName;
	}

	/**
	 * Sets the value of the middleName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMiddleName(String value) {
		this.middleName = value;
	}

	/**
	 * Gets the value of the aliasLastName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAliasLastName() {
		return aliasLastName;
	}

	/**
	 * Sets the value of the aliasLastName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAliasLastName(String value) {
		this.aliasLastName = value;
	}

	/**
	 * Gets the value of the aliasFirstName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAliasFirstName() {
		return aliasFirstName;
	}

	/**
	 * Sets the value of the aliasFirstName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAliasFirstName(String value) {
		this.aliasFirstName = value;
	}

	/**
	 * Gets the value of the moniker property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMoniker() {
		return moniker;
	}

	/**
	 * Sets the value of the moniker property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMoniker(String value) {
		this.moniker = value;
	}

	/**
	 * Gets the value of the zip property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * Sets the value of the zip property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setZip(String value) {
		this.zip = value;
	}

	/**
	 * Gets the value of the birthState property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBirthState() {
		return birthState;
	}

	/**
	 * Sets the value of the birthState property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBirthState(String value) {
		this.birthState = value;
	}

	/**
	 * Gets the value of the heightInInches property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeightInInches() {
		return heightInInches;
	}

	/**
	 * Sets the value of the heightInInches property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeightInInches(String value) {
		this.heightInInches = value;
	}

	/**
	 * Gets the value of the weight property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWeight() {
		return weight;
	}

	/**
	 * Sets the value of the weight property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWeight(String value) {
		this.weight = value;
	}

	/**
	 * Gets the value of the ssn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSSN() {
		return ssn;
	}

	/**
	 * Sets the value of the ssn property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSSN(String value) {
		this.ssn = value;
	}

	/**
	 * Gets the value of the ciiNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCIINumber() {
		return ciiNumber;
	}

	/**
	 * Sets the value of the ciiNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCIINumber(String value) {
		this.ciiNumber = value;
	}

	/**
	 * Gets the value of the fbiNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFBINumber() {
		return fbiNumber;
	}

	/**
	 * Sets the value of the fbiNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFBINumber(String value) {
		this.fbiNumber = value;
	}

	/**
	 * Gets the value of the licensePlate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLicensePlate() {
		return licensePlate;
	}

	/**
	 * Sets the value of the licensePlate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLicensePlate(String value) {
		this.licensePlate = value;
	}

	/**
	 * Gets the value of the dateOfBirth property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDateOfBirth() {
		return dateOfBirth;
	}

	/**
	 * Sets the value of the dateOfBirth property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDateOfBirth(String value) {
		this.dateOfBirth = value;
	}

	/**
	 * Gets the value of the paroleeReleaseDate property.
	 * 
	 * @return possible object is {@link ParoleeReleaseDate }
	 * 
	 */
	public ParoleeReleaseDate getParoleeReleaseDate() {
		return paroleeReleaseDate;
	}

	/**
	 * Sets the value of the paroleeReleaseDate property.
	 * 
	 * @param value
	 *            allowed object is {@link ParoleeReleaseDate }
	 * 
	 */
	public void setParoleeReleaseDate(ParoleeReleaseDate value) {
		this.paroleeReleaseDate = value;
	}

	/**
	 * Gets the value of the vehicleYear property.
	 * 
	 * @return possible object is {@link VehicleYear }
	 * 
	 */
	public VehicleYear getVehicleYear() {
		return vehicleYear;
	}

	/**
	 * Sets the value of the vehicleYear property.
	 * 
	 * @param value
	 *            allowed object is {@link VehicleYear }
	 * 
	 */
	public void setVehicleYear(VehicleYear value) {
		this.vehicleYear = value;
	}

	/**
	 * Gets the value of the ethnicity property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEthnicity() {
		return ethnicity;
	}

	/**
	 * Sets the value of the ethnicity property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEthnicity(String value) {
		this.ethnicity = value;
	}

	/**
	 * Gets the value of the hairColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHairColor() {
		return hairColor;
	}

	/**
	 * Sets the value of the hairColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHairColor(String value) {
		this.hairColor = value;
	}

	/**
	 * Gets the value of the pc290SexOff property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPC290SexOff() {
		return pc290SexOff;
	}

	/**
	 * Sets the value of the pc290SexOff property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPC290SexOff(String value) {
		this.pc290SexOff = value;
	}

	/**
	 * Gets the value of the pc4571Arson property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPC4571Arson() {
		return pc4571Arson;
	}

	/**
	 * Sets the value of the pc4571Arson property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPC4571Arson(String value) {
		this.pc4571Arson = value;
	}

	/**
	 * Gets the value of the pc11590Drugs property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPC11590Drugs() {
		return pc11590Drugs;
	}

	/**
	 * Sets the value of the pc11590Drugs property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPC11590Drugs(String value) {
		this.pc11590Drugs = value;
	}

	/**
	 * Gets the value of the pc30586FelonyViolation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPC30586FelonyViolation() {
		return pc30586FelonyViolation;
	}

	/**
	 * Sets the value of the pc30586FelonyViolation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPC30586FelonyViolation(String value) {
		this.pc30586FelonyViolation = value;
	}

	/**
	 * Gets the value of the smt property.
	 * 
	 * @return possible object is {@link SMT }
	 * 
	 */
	public SMT getSMT() {
		return smt;
	}

	/**
	 * Sets the value of the smt property.
	 * 
	 * @param value
	 *            allowed object is {@link SMT }
	 * 
	 */
	public void setSMT(SMT value) {
		this.smt = value;
	}

	/**
	 * Gets the value of the commitmentOffense property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCommitmentOffense() {
		return commitmentOffense;
	}

	/**
	 * Sets the value of the commitmentOffense property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCommitmentOffense(String value) {
		this.commitmentOffense = value;
	}

	/**
	 * Gets the value of the countyOfLLR property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountyOfLLR() {
		return countyOfLLR;
	}

	/**
	 * Sets the value of the countyOfLLR property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountyOfLLR(String value) {
		this.countyOfLLR = value;
	}

	/**
	 * Gets the value of the unitCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnitCode() {
		return unitCode;
	}

	/**
	 * Sets the value of the unitCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnitCode(String value) {
		this.unitCode = value;
	}

}
