//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.25 at 10:43:25 PM PDT 
//


package plm.ws.mtom.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the plm.ws.mtom.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InternalParoleeDataResponse_QNAME = new QName("http://www.plm/ws/mtom/data", "InternalParoleeDataResponse");
    private final static QName _InternalParoleeDataRequest_QNAME = new QName("http://www.plm/ws/mtom/data", "InternalParoleeDataRequest");
    private final static QName _IncludeAttachment_QNAME = new QName("http://www.plm/ws/mtom/data", "IncludeAttachment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: plm.ws.mtom.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SMT }
     * 
     */
    public SMT createSMT() {
        return new SMT();
    }

    /**
     * Create an instance of {@link InternalParoleeDataResponse }
     * 
     */
    public InternalParoleeDataResponse createInternalParoleeDataResponse() {
        return new InternalParoleeDataResponse();
    }

    /**
     * Create an instance of {@link DataAttachment }
     * 
     */
    public DataAttachment createDataAttachment() {
        return new DataAttachment();
    }

    /**
     * Create an instance of {@link ParoleeReleaseDate }
     * 
     */
    public ParoleeReleaseDate createParoleeReleaseDate() {
        return new ParoleeReleaseDate();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link InternalParoleeDataRequest }
     * 
     */
    public InternalParoleeDataRequest createInternalParoleeDataRequest() {
        return new InternalParoleeDataRequest();
    }

    /**
     * Create an instance of {@link VehicleYear }
     * 
     */
    public VehicleYear createVehicleYear() {
        return new VehicleYear();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternalParoleeDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/data", name = "InternalParoleeDataResponse")
    public JAXBElement<InternalParoleeDataResponse> createInternalParoleeDataResponse(InternalParoleeDataResponse value) {
        return new JAXBElement<InternalParoleeDataResponse>(_InternalParoleeDataResponse_QNAME, InternalParoleeDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternalParoleeDataRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/data", name = "InternalParoleeDataRequest")
    public JAXBElement<InternalParoleeDataRequest> createInternalParoleeDataRequest(InternalParoleeDataRequest value) {
        return new JAXBElement<InternalParoleeDataRequest>(_InternalParoleeDataRequest_QNAME, InternalParoleeDataRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/data", name = "IncludeAttachment")
    public JAXBElement<String> createIncludeAttachment(String value) {
        return new JAXBElement<String>(_IncludeAttachment_QNAME, String.class, null, value);
    }

}
