-------------------------------------------------------------------------- 
-- Script Name - plm-cpwoner-grant.sql
-- Purpose 
-- This script grants access for the listed CPOWNER tables to PLMOWNER 
-- History
-- 11/18/2009 - Tushar Dalal - Initial version
-- 02/10/2010 - Madhu Menon  - Added AB3_UNIT table
-- 02/10/2010 - Madhu Menon  - Removed TRANSFER* tables
-------------------------------------------------------------------------- 
--- Grants needs to be given from the CPOWNER Schema ---

GRANT SELECT ON ADDRESS TO PLMOWNER;
GRANT SELECT ON AGENT TO PLMOWNER;
GRANT SELECT ON ALIAS TO PLMOWNER;
GRANT SELECT ON CLASSIFICATION TO PLMOWNER;
GRANT SELECT ON COUNTY TO PLMOWNER;
GRANT SELECT ON EYECOLOR TO PLMOWNER;
GRANT SELECT ON HAIRCOLOR TO PLMOWNER;
GRANT SELECT ON JOB TO PLMOWNER;
GRANT SELECT ON MONIKER TO PLMOWNER;
GRANT SELECT ON OFFENSE TO PLMOWNER;
GRANT SELECT ON OFFENSE_TYPE TO PLMOWNER;
GRANT SELECT ON PAROLEE TO PLMOWNER;
GRANT SELECT ON PROBLEM_AREA TO PLMOWNER;
GRANT SELECT ON RACE TO PLMOWNER;
GRANT SELECT ON SMT TO PLMOWNER;
GRANT SELECT ON SMT_TYPE TO PLMOWNER;
GRANT SELECT ON SPECIAL_CONDITION TO PLMOWNER;
GRANT SELECT ON STANDARD_CONDITION TO PLMOWNER;
GRANT SELECT ON STATE TO PLMOWNER;
GRANT SELECT ON UNIT TO PLMOWNER;
GRANT SELECT ON VEHICLE TO PLMOWNER;
GRANT SELECT ON VEHICLE_COLOR TO PLMOWNER;
GRANT SELECT ON VEHICLE_MAKE TO PLMOWNER;
GRANT SELECT ON VEHICLE_STYLE TO PLMOWNER;
GRANT SELECT ON AB3_UNIT TO PLMOWNER;