//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.25 at 09:53:30 PM PDT 
//


package plm.ws.mtom.auth;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the plm.ws.mtom.auth package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ParoleeInfoResponse_QNAME = new QName("http://www.plm/ws/mtom/auth", "ParoleeInfoResponse");
    private final static QName _UpdateAvailable_QNAME = new QName("http://www.plm/ws/mtom/auth", "UpdateAvailable");
    private final static QName _ServiceRequestType_QNAME = new QName("http://www.plm/ws/mtom/auth", "ServiceRequestType");
    private final static QName _ParoleeInfoRequest_QNAME = new QName("http://www.plm/ws/mtom/auth", "ParoleeInfoRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: plm.ws.mtom.auth
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParoleeReleaseDate }
     * 
     */
    public ParoleeReleaseDate createParoleeReleaseDate() {
        return new ParoleeReleaseDate();
    }

    /**
     * Create an instance of {@link ParoleeInfoResponse }
     * 
     */
    public ParoleeInfoResponse createParoleeInfoResponse() {
        return new ParoleeInfoResponse();
    }

    /**
     * Create an instance of {@link SMT }
     * 
     */
    public SMT createSMT() {
        return new SMT();
    }

    /**
     * Create an instance of {@link VehicleYear }
     * 
     */
    public VehicleYear createVehicleYear() {
        return new VehicleYear();
    }

    /**
     * Create an instance of {@link DataAttachment }
     * 
     */
    public DataAttachment createDataAttachment() {
        return new DataAttachment();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link ParoleeInfoRequest }
     * 
     */
    public ParoleeInfoRequest createParoleeInfoRequest() {
        return new ParoleeInfoRequest();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParoleeInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/auth", name = "ParoleeInfoResponse")
    public JAXBElement<ParoleeInfoResponse> createParoleeInfoResponse(ParoleeInfoResponse value) {
        return new JAXBElement<ParoleeInfoResponse>(_ParoleeInfoResponse_QNAME, ParoleeInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/auth", name = "UpdateAvailable")
    public JAXBElement<String> createUpdateAvailable(String value) {
        return new JAXBElement<String>(_UpdateAvailable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/auth", name = "ServiceRequestType")
    public JAXBElement<String> createServiceRequestType(String value) {
        return new JAXBElement<String>(_ServiceRequestType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParoleeInfoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/auth", name = "ParoleeInfoRequest")
    public JAXBElement<ParoleeInfoRequest> createParoleeInfoRequest(ParoleeInfoRequest value) {
        return new JAXBElement<ParoleeInfoRequest>(_ParoleeInfoRequest_QNAME, ParoleeInfoRequest.class, null, value);
    }

}
