//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 04:14:50 PM PST 
//


package plm.ws.mtom.paroleedata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="last-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="first-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="middle-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdc-num" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parole-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parole-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="max-discharge-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="revocation-release-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="supervision-level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commitment-county" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parole-unit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="agent-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="agent-phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="agent-email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="birth-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="birth-state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ethnicity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hair-color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eye-color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fbi-num" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cii-num" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ssa-num" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="driver-license-num" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lastName",
    "firstName",
    "middleName",
    "cdcNum",
    "paroleStatus",
    "paroleDate",
    "maxDischargeDate",
    "revocationReleaseDate",
    "supervisionLevel",
    "commitmentCounty",
    "paroleUnit",
    "agentName",
    "agentPhone",
    "agentEmail",
    "birthDate",
    "birthState",
    "gender",
    "ethnicity",
    "height",
    "weight",
    "hairColor",
    "eyeColor",
    "fbiNum",
    "ciiNum",
    "ssaNum",
    "driverLicenseNum"
})
@XmlRootElement(name = "identity")
public class Identity {

    @XmlElement(name = "last-name")
    protected String lastName;
    @XmlElement(name = "first-name")
    protected String firstName;
    @XmlElement(name = "middle-name")
    protected String middleName;
    @XmlElement(name = "cdc-num")
    protected String cdcNum;
    @XmlElement(name = "parole-status")
    protected String paroleStatus;
    @XmlElement(name = "parole-date")
    protected String paroleDate;
    @XmlElement(name = "max-discharge-date")
    protected String maxDischargeDate;
    @XmlElement(name = "revocation-release-date")
    protected String revocationReleaseDate;
    @XmlElement(name = "supervision-level")
    protected String supervisionLevel;
    @XmlElement(name = "commitment-county")
    protected String commitmentCounty;
    @XmlElement(name = "parole-unit")
    protected String paroleUnit;
    @XmlElement(name = "agent-name")
    protected String agentName;
    @XmlElement(name = "agent-phone")
    protected String agentPhone;
    @XmlElement(name = "agent-email")
    protected String agentEmail;
    @XmlElement(name = "birth-date")
    protected String birthDate;
    @XmlElement(name = "birth-state")
    protected String birthState;
    protected String gender;
    protected String ethnicity;
    protected String height;
    protected String weight;
    @XmlElement(name = "hair-color")
    protected String hairColor;
    @XmlElement(name = "eye-color")
    protected String eyeColor;
    @XmlElement(name = "fbi-num")
    protected String fbiNum;
    @XmlElement(name = "cii-num")
    protected String ciiNum;
    @XmlElement(name = "ssa-num")
    protected String ssaNum;
    @XmlElement(name = "driver-license-num")
    protected String driverLicenseNum;

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the cdcNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdcNum() {
        return cdcNum;
    }

    /**
     * Sets the value of the cdcNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdcNum(String value) {
        this.cdcNum = value;
    }

    /**
     * Gets the value of the paroleStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParoleStatus() {
        return paroleStatus;
    }

    /**
     * Sets the value of the paroleStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParoleStatus(String value) {
        this.paroleStatus = value;
    }

    /**
     * Gets the value of the paroleDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParoleDate() {
        return paroleDate;
    }

    /**
     * Sets the value of the paroleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParoleDate(String value) {
        this.paroleDate = value;
    }

    /**
     * Gets the value of the maxDischargeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxDischargeDate() {
        return maxDischargeDate;
    }

    /**
     * Sets the value of the maxDischargeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxDischargeDate(String value) {
        this.maxDischargeDate = value;
    }

    /**
     * Gets the value of the revocationReleaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevocationReleaseDate() {
        return revocationReleaseDate;
    }

    /**
     * Sets the value of the revocationReleaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevocationReleaseDate(String value) {
        this.revocationReleaseDate = value;
    }

    /**
     * Gets the value of the supervisionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisionLevel() {
        return supervisionLevel;
    }

    /**
     * Sets the value of the supervisionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisionLevel(String value) {
        this.supervisionLevel = value;
    }

    /**
     * Gets the value of the commitmentCounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommitmentCounty() {
        return commitmentCounty;
    }

    /**
     * Sets the value of the commitmentCounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitmentCounty(String value) {
        this.commitmentCounty = value;
    }

    /**
     * Gets the value of the paroleUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParoleUnit() {
        return paroleUnit;
    }

    /**
     * Sets the value of the paroleUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParoleUnit(String value) {
        this.paroleUnit = value;
    }

    /**
     * Gets the value of the agentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * Sets the value of the agentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentName(String value) {
        this.agentName = value;
    }

    /**
     * Gets the value of the agentPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentPhone() {
        return agentPhone;
    }

    /**
     * Sets the value of the agentPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentPhone(String value) {
        this.agentPhone = value;
    }

    /**
     * Gets the value of the agentEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentEmail() {
        return agentEmail;
    }

    /**
     * Sets the value of the agentEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentEmail(String value) {
        this.agentEmail = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthState() {
        return birthState;
    }

    /**
     * Sets the value of the birthState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthState(String value) {
        this.birthState = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEthnicity(String value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(String value) {
        this.weight = value;
    }

    /**
     * Gets the value of the hairColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHairColor() {
        return hairColor;
    }

    /**
     * Sets the value of the hairColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHairColor(String value) {
        this.hairColor = value;
    }

    /**
     * Gets the value of the eyeColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEyeColor() {
        return eyeColor;
    }

    /**
     * Sets the value of the eyeColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEyeColor(String value) {
        this.eyeColor = value;
    }

    /**
     * Gets the value of the fbiNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFbiNum() {
        return fbiNum;
    }

    /**
     * Sets the value of the fbiNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFbiNum(String value) {
        this.fbiNum = value;
    }

    /**
     * Gets the value of the ciiNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiiNum() {
        return ciiNum;
    }

    /**
     * Sets the value of the ciiNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiiNum(String value) {
        this.ciiNum = value;
    }

    /**
     * Gets the value of the ssaNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsaNum() {
        return ssaNum;
    }

    /**
     * Sets the value of the ssaNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsaNum(String value) {
        this.ssaNum = value;
    }

    /**
     * Gets the value of the driverLicenseNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverLicenseNum() {
        return driverLicenseNum;
    }

    /**
     * Sets the value of the driverLicenseNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverLicenseNum(String value) {
        this.driverLicenseNum = value;
    }

}
