//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 04:14:50 PM PST 
//


package plm.ws.mtom.paroleedata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import plm.ws.mtom.data.InternalParoleeDataResponse;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the plm.ws.mtom.paroleedata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _ParoleeDataSet_QNAME = new QName("http://www.plm/ws/mtom/paroleedata", "ParoleeDataSet");
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: plm.ws.mtom.paroleedata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Aliases }
     * 
     */
    public Aliases createAliases() {
        return new Aliases();
    }

    /**
     * Create an instance of {@link CommitmentOffenses }
     * 
     */
    public CommitmentOffenses createCommitmentOffenses() {
        return new CommitmentOffenses();
    }

    /**
     * Create an instance of {@link SpecialConditions }
     * 
     */
    public SpecialConditions createSpecialConditions() {
        return new SpecialConditions();
    }

    /**
     * Create an instance of {@link Smt }
     * 
     */
    public Smt createSmt() {
        return new Smt();
    }

    /**
     * Create an instance of {@link OtherSpecialConditions }
     * 
     */
    public OtherSpecialConditions createOtherSpecialConditions() {
        return new OtherSpecialConditions();
    }

    /**
     * Create an instance of {@link Parolee }
     * 
     */
    public Parolee createParolee() {
        return new Parolee();
    }

    /**
     * Create an instance of {@link Alias }
     * 
     */
    public Alias createAlias() {
        return new Alias();
    }

    /**
     * Create an instance of {@link Vehicles }
     * 
     */
    public Vehicles createVehicles() {
        return new Vehicles();
    }

    /**
     * Create an instance of {@link Identity }
     * 
     */
    public Identity createIdentity() {
        return new Identity();
    }

    /**
     * Create an instance of {@link Smts }
     * 
     */
    public Smts createSmts() {
        return new Smts();
    }

    /**
     * Create an instance of {@link OtherSpecialCondition }
     * 
     */
    public OtherSpecialCondition createOtherSpecialCondition() {
        return new OtherSpecialCondition();
    }

    /**
     * Create an instance of {@link CommitmentOffense }
     * 
     */
    public CommitmentOffense createCommitmentOffense() {
        return new CommitmentOffense();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link RegistrationNotice }
     * 
     */
    public RegistrationNotice createRegistrationNotice() {
        return new RegistrationNotice();
    }

    /**
     * Create an instance of {@link ParoleeDataSet }
     * 
     */
    public ParoleeDataSet createParoleeDataSet() {
        return new ParoleeDataSet();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link Moniker }
     * 
     */
    public Moniker createMoniker() {
        return new Moniker();
    }

    /**
     * Create an instance of {@link Monikers }
     * 
     */
    public Monikers createMonikers() {
        return new Monikers();
    }

    /**
     * Create an instance of {@link Addresses }
     * 
     */
    public Addresses createAddresses() {
        return new Addresses();
    }
    
    @XmlElementDecl(namespace = "http://www.plm/ws/mtom/paroleedata", name = "ParoleeDataSet")
    public JAXBElement<ParoleeDataSet> createParoleeDataSet(ParoleeDataSet value) {
        return new JAXBElement<ParoleeDataSet>(_ParoleeDataSet_QNAME, ParoleeDataSet.class, null, value);
    }

}
