//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 04:14:50 PM PST 
//


package plm.ws.mtom.paroleedata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}identity" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}registration-notice" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}special-conditions" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}addresses" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}smts" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}aliases" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}monikers" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}commitment-offenses" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}jobs" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}vehicles" minOccurs="0"/>
 *         &lt;element ref="{http://www.plm/ws/mtom/paroleedata}other-special-conditions" minOccurs="0"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identity",
    "registrationNotice",
    "specialConditions",
    "addresses",
    "smts",
    "aliases",
    "monikers",
    "commitmentOffenses",
    "jobs",
    "vehicles",
    "otherSpecialConditions",
    "comments"
})
@XmlRootElement(name = "parolee")
public class Parolee {

    protected Identity identity;
    @XmlElement(name = "registration-notice")
    protected RegistrationNotice registrationNotice;
    @XmlElement(name = "special-conditions")
    protected SpecialConditions specialConditions;
    protected Addresses addresses;
    protected Smts smts;
    protected Aliases aliases;
    protected Monikers monikers;
    @XmlElement(name = "commitment-offenses")
    protected CommitmentOffenses commitmentOffenses;
    protected Jobs jobs;
    protected Vehicles vehicles;
    @XmlElement(name = "other-special-conditions")
    protected OtherSpecialConditions otherSpecialConditions;
    protected String comments;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link Identity }
     *     
     */
    public Identity getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identity }
     *     
     */
    public void setIdentity(Identity value) {
        this.identity = value;
    }

    /**
     * Gets the value of the registrationNotice property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationNotice }
     *     
     */
    public RegistrationNotice getRegistrationNotice() {
        return registrationNotice;
    }

    /**
     * Sets the value of the registrationNotice property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationNotice }
     *     
     */
    public void setRegistrationNotice(RegistrationNotice value) {
        this.registrationNotice = value;
    }

    /**
     * Gets the value of the specialConditions property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialConditions }
     *     
     */
    public SpecialConditions getSpecialConditions() {
        return specialConditions;
    }

    /**
     * Sets the value of the specialConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialConditions }
     *     
     */
    public void setSpecialConditions(SpecialConditions value) {
        this.specialConditions = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link Addresses }
     *     
     */
    public Addresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addresses }
     *     
     */
    public void setAddresses(Addresses value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the smts property.
     * 
     * @return
     *     possible object is
     *     {@link Smts }
     *     
     */
    public Smts getSmts() {
        return smts;
    }

    /**
     * Sets the value of the smts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Smts }
     *     
     */
    public void setSmts(Smts value) {
        this.smts = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link Aliases }
     *     
     */
    public Aliases getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aliases }
     *     
     */
    public void setAliases(Aliases value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the monikers property.
     * 
     * @return
     *     possible object is
     *     {@link Monikers }
     *     
     */
    public Monikers getMonikers() {
        return monikers;
    }

    /**
     * Sets the value of the monikers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Monikers }
     *     
     */
    public void setMonikers(Monikers value) {
        this.monikers = value;
    }

    /**
     * Gets the value of the commitmentOffenses property.
     * 
     * @return
     *     possible object is
     *     {@link CommitmentOffenses }
     *     
     */
    public CommitmentOffenses getCommitmentOffenses() {
        return commitmentOffenses;
    }

    /**
     * Sets the value of the commitmentOffenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommitmentOffenses }
     *     
     */
    public void setCommitmentOffenses(CommitmentOffenses value) {
        this.commitmentOffenses = value;
    }

    /**
     * Gets the value of the jobs property.
     * 
     * @return
     *     possible object is
     *     {@link Jobs }
     *     
     */
    public Jobs getJobs() {
        return jobs;
    }

    /**
     * Sets the value of the jobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jobs }
     *     
     */
    public void setJobs(Jobs value) {
        this.jobs = value;
    }

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link Vehicles }
     *     
     */
    public Vehicles getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vehicles }
     *     
     */
    public void setVehicles(Vehicles value) {
        this.vehicles = value;
    }

    /**
     * Gets the value of the otherSpecialConditions property.
     * 
     * @return
     *     possible object is
     *     {@link OtherSpecialConditions }
     *     
     */
    public OtherSpecialConditions getOtherSpecialConditions() {
        return otherSpecialConditions;
    }

    /**
     * Sets the value of the otherSpecialConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherSpecialConditions }
     *     
     */
    public void setOtherSpecialConditions(OtherSpecialConditions value) {
        this.otherSpecialConditions = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
